/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.hotel.gui;

import br.com.senac.hotel.web.persistencia.QuartosDAO;
import br.com.senac.hotel.web.persistencia.ReservaDAO;
import br.com.senac.hotel.web.Models.Quartos;
import br.com.senac.hotel.web.Models.Reserva;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aulas
 */
public class TelaAdicionarReserva extends javax.swing.JFrame {

    private static TelaPrincipalAdmin telaPrincipal;
    private static List<Reserva> reservasList;
    ReservaDAO reservaDao = new ReservaDAO();

    /**
     * Creates new form TelaAdicionarQuarto
     *
     * @param reservasList
     * @param telaPrincipal
     */
    public TelaAdicionarReserva(List<Reserva> reservasList, TelaPrincipalAdmin telaPrincipal) {
        initComponents();
        this.reservasList = reservasList;
        this.telaPrincipal = telaPrincipal;
        carregarProximoId();
    }

    private void carregarProximoId() {
        Integer proximoId = reservaDao.obterProximoId();
        txtId.setText(proximoId.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblReservas = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblIdHospede = new javax.swing.JLabel();
        txtIdHospede = new javax.swing.JTextField();
        lblIdQuarto = new javax.swing.JLabel();
        txtIdQuarto = new javax.swing.JTextField();
        lblCheckin = new javax.swing.JLabel();
        lblPrevCheckout = new javax.swing.JLabel();
        lblCheckout = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtPrevCheckout = new javax.swing.JFormattedTextField();
        txtCheckin = new javax.swing.JFormattedTextField();
        txtCheckout = new javax.swing.JFormattedTextField();
        lblStatus = new javax.swing.JLabel();
        ckbStatus = new javax.swing.JComboBox<>();
        lblPagamento = new javax.swing.JLabel();
        ckbPagamento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReservas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReservas.setText("RESERVAS");

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("ID:");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblIdHospede.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdHospede.setText("ID Hóspede:");

        lblIdQuarto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdQuarto.setText("ID Quarto:");

        lblCheckin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCheckin.setText("Check-in:");

        lblPrevCheckout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrevCheckout.setText("Prev. Check-out:");

        lblCheckout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCheckout.setText("Check-out:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtPrevCheckout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtPrevCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrevCheckoutActionPerformed(evt);
            }
        });

        txtCheckin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckinActionPerformed(evt);
            }
        });

        txtCheckout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckoutActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setText("Status:");

        ckbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confirmado", "Pendente", "Cancelado" }));

        lblPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPagamento.setText("Pagamento:");

        ckbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de crédito", "Cartão de débito" }));
        ckbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblReservas))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvar)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdHospede)
                                    .addComponent(lblId)
                                    .addComponent(lblIdQuarto)
                                    .addComponent(lblCheckin)
                                    .addComponent(lblPrevCheckout)
                                    .addComponent(lblCheckout)
                                    .addComponent(lblStatus)
                                    .addComponent(lblPagamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdHospede, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(txtId)
                                    .addComponent(txtIdQuarto)
                                    .addComponent(txtPrevCheckout)
                                    .addComponent(txtCheckin)
                                    .addComponent(txtCheckout)
                                    .addComponent(ckbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdHospede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdQuarto)
                    .addComponent(txtIdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckin)
                    .addComponent(txtCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrevCheckout)
                    .addComponent(txtPrevCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckout)
                    .addComponent(txtCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(ckbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagamento)
                    .addComponent(ckbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            int hospedeId = Integer.parseInt(txtIdHospede.getText());
            int quartoId = Integer.parseInt(txtIdQuarto.getText());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate checkin = LocalDate.parse(txtCheckin.getText(), formatter);
            LocalDate prevCheckout = LocalDate.parse(txtPrevCheckout.getText(), formatter);
            LocalDate checkout = null;
            if (txtCheckout.getText() != null && !txtCheckout.getText().trim().isEmpty()) {
                checkout = LocalDate.parse(txtCheckout.getText(), formatter);
            }
            int statusSelecionado = ckbStatus.getSelectedIndex();
            switch (statusSelecionado) {
                case 0:
                    statusSelecionado = 1; // Confirmado
                    break;
                case 1:
                    statusSelecionado = 2; // Pendente
                    break;
                case 2:
                    statusSelecionado = 3; // Cancelado
                    break;
                default:
                    throw new IllegalArgumentException("Status inválido selecionado!");
            }

            String pagamento = (String) ckbPagamento.getSelectedItem();

            String text = txtId.getText();
            Integer id = (text == null || text.isEmpty()) ? 0 : Integer.valueOf(text);

            if (!reservaDao.getDisponibilidadeQuarto(quartoId, checkin, prevCheckout)) {
                JOptionPane.showMessageDialog(this, "Quarto não está disponível nesta data. ");
                return;
            }

            Reserva novaReserva = new Reserva(id, hospedeId, quartoId, checkin, prevCheckout, checkout, statusSelecionado, pagamento);
            reservaDao.cadastrar(novaReserva);
            telaPrincipal.adicionarReserva(novaReserva);
            JOptionPane.showMessageDialog(this, "Reserva cadastrada com sucesso. ");
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha os campos corretamente. " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtPrevCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrevCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrevCheckoutActionPerformed

    private void txtCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckinActionPerformed

    private void txtCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckoutActionPerformed

    private void ckbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarReserva(reservasList, telaPrincipal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> ckbPagamento;
    private javax.swing.JComboBox<String> ckbStatus;
    private javax.swing.JLabel lblCheckin;
    private javax.swing.JLabel lblCheckout;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdHospede;
    private javax.swing.JLabel lblIdQuarto;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblPrevCheckout;
    private javax.swing.JLabel lblReservas;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JFormattedTextField txtCheckin;
    private javax.swing.JFormattedTextField txtCheckout;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdHospede;
    private javax.swing.JTextField txtIdQuarto;
    private javax.swing.JFormattedTextField txtPrevCheckout;
    // End of variables declaration//GEN-END:variables
}
